# Generated by Django 4.0.3 on 2022-03-10 15:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_root_img),
        ),
    ]
