# Generated by Django 4.1.1 on 2022-09-17 14:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_root),
        ),
    ]
