# Generated by Django 4.1.1 on 2022-09-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_collection_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_prob', models.FloatField(blank=True, default=0.5, null=True)),
                ('a_views', models.IntegerField(blank=True, default=0, null=True)),
                ('a_views_conv', models.IntegerField(blank=True, default=0, null=True)),
                ('a_conversion', models.FloatField(blank=True, default=0, null=True)),
                ('a_ci_bot', models.FloatField(blank=True, default=0, null=True)),
                ('a_ci_top', models.FloatField(blank=True, default=0, null=True)),
                ('b_prob', models.FloatField(blank=True, default=0.5, null=True)),
                ('b_views', models.IntegerField(blank=True, default=0, null=True)),
                ('b_views_conv', models.IntegerField(blank=True, default=0, null=True)),
                ('b_conversion', models.FloatField(blank=True, default=0, null=True)),
                ('b_ci_bot', models.FloatField(blank=True, default=0, null=True)),
                ('b_ci_top', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
